spring.application.name=credit

spring.mvc.static-path-pattern=/static/**

spring.datasource.url=jdbc:postgresql://localhost:5432/credit_app_local
spring.datasource.username=credit_app
spring.datasource.password=credit_app

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

#fileupload
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
spring.servlet.multipart.enabled=true

storage.upload.path=src\\main\\resources\\storage
