CREATE TABLE IF NOT EXISTS loan_product (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	rate DOUBLE PRECISION NOT NULL,
	min_term BIGINT NOT NULL,
	max_term BIGINT NOT NULL,
	min_amount BIGINT NOT NULL,
	max_amount BIGINT NOT NULL
);